/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type CreatePayableBatchItemRequest = {
    bulkPayableItemCreate?: shared.BulkPayableItemCreate | undefined;
    /**
     * Unique identifier for a batch
     */
    batchId: string;
};

export type CreatePayableBatchItemResponse = {
    /**
     * An item that will be converted into a payable
     */
    bulkPayableItem?: shared.BulkPayableItem | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const CreatePayableBatchItemRequest$inboundSchema: z.ZodType<
    CreatePayableBatchItemRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        BulkPayableItemCreate: shared.BulkPayableItemCreate$inboundSchema.optional(),
        batchId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            BulkPayableItemCreate: "bulkPayableItemCreate",
        });
    });

/** @internal */
export type CreatePayableBatchItemRequest$Outbound = {
    BulkPayableItemCreate?: shared.BulkPayableItemCreate$Outbound | undefined;
    batchId: string;
};

/** @internal */
export const CreatePayableBatchItemRequest$outboundSchema: z.ZodType<
    CreatePayableBatchItemRequest$Outbound,
    z.ZodTypeDef,
    CreatePayableBatchItemRequest
> = z
    .object({
        bulkPayableItemCreate: shared.BulkPayableItemCreate$outboundSchema.optional(),
        batchId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            bulkPayableItemCreate: "BulkPayableItemCreate",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePayableBatchItemRequest$ {
    /** @deprecated use `CreatePayableBatchItemRequest$inboundSchema` instead. */
    export const inboundSchema = CreatePayableBatchItemRequest$inboundSchema;
    /** @deprecated use `CreatePayableBatchItemRequest$outboundSchema` instead. */
    export const outboundSchema = CreatePayableBatchItemRequest$outboundSchema;
    /** @deprecated use `CreatePayableBatchItemRequest$Outbound` instead. */
    export type Outbound = CreatePayableBatchItemRequest$Outbound;
}

/** @internal */
export const CreatePayableBatchItemResponse$inboundSchema: z.ZodType<
    CreatePayableBatchItemResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        BulkPayableItem: shared.BulkPayableItem$inboundSchema.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            BulkPayableItem: "bulkPayableItem",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type CreatePayableBatchItemResponse$Outbound = {
    BulkPayableItem?: shared.BulkPayableItem$Outbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const CreatePayableBatchItemResponse$outboundSchema: z.ZodType<
    CreatePayableBatchItemResponse$Outbound,
    z.ZodTypeDef,
    CreatePayableBatchItemResponse
> = z
    .object({
        bulkPayableItem: shared.BulkPayableItem$outboundSchema.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            bulkPayableItem: "BulkPayableItem",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePayableBatchItemResponse$ {
    /** @deprecated use `CreatePayableBatchItemResponse$inboundSchema` instead. */
    export const inboundSchema = CreatePayableBatchItemResponse$inboundSchema;
    /** @deprecated use `CreatePayableBatchItemResponse$outboundSchema` instead. */
    export const outboundSchema = CreatePayableBatchItemResponse$outboundSchema;
    /** @deprecated use `CreatePayableBatchItemResponse$Outbound` instead. */
    export type Outbound = CreatePayableBatchItemResponse$Outbound;
}
