/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type CreateClientDeductionResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * A deduction
   */
  deductionResponse?: shared.DeductionResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const CreateClientDeductionResponse$inboundSchema: z.ZodType<
  CreateClientDeductionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  DeductionResponse: shared.DeductionResponse$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "DeductionResponse": "deductionResponse",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type CreateClientDeductionResponse$Outbound = {
  ContentType: string;
  DeductionResponse?: shared.DeductionResponse$Outbound | undefined;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const CreateClientDeductionResponse$outboundSchema: z.ZodType<
  CreateClientDeductionResponse$Outbound,
  z.ZodTypeDef,
  CreateClientDeductionResponse
> = z.object({
  contentType: z.string(),
  deductionResponse: shared.DeductionResponse$outboundSchema.optional(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    deductionResponse: "DeductionResponse",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateClientDeductionResponse$ {
  /** @deprecated use `CreateClientDeductionResponse$inboundSchema` instead. */
  export const inboundSchema = CreateClientDeductionResponse$inboundSchema;
  /** @deprecated use `CreateClientDeductionResponse$outboundSchema` instead. */
  export const outboundSchema = CreateClientDeductionResponse$outboundSchema;
  /** @deprecated use `CreateClientDeductionResponse$Outbound` instead. */
  export type Outbound = CreateClientDeductionResponse$Outbound;
}

export function createClientDeductionResponseToJSON(
  createClientDeductionResponse: CreateClientDeductionResponse,
): string {
  return JSON.stringify(
    CreateClientDeductionResponse$outboundSchema.parse(
      createClientDeductionResponse,
    ),
  );
}

export function createClientDeductionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateClientDeductionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateClientDeductionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateClientDeductionResponse' from JSON`,
  );
}
