/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type GetBankStatementRequest = {
    /**
     * Unique identifier
     */
    id: string;
};

export type GetBankStatementResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * A list of bank statements
     */
    classes?: Array<shared.BankStatement> | undefined;
};

/** @internal */
export const GetBankStatementRequest$inboundSchema: z.ZodType<
    GetBankStatementRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
});

/** @internal */
export type GetBankStatementRequest$Outbound = {
    id: string;
};

/** @internal */
export const GetBankStatementRequest$outboundSchema: z.ZodType<
    GetBankStatementRequest$Outbound,
    z.ZodTypeDef,
    GetBankStatementRequest
> = z.object({
    id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBankStatementRequest$ {
    /** @deprecated use `GetBankStatementRequest$inboundSchema` instead. */
    export const inboundSchema = GetBankStatementRequest$inboundSchema;
    /** @deprecated use `GetBankStatementRequest$outboundSchema` instead. */
    export const outboundSchema = GetBankStatementRequest$outboundSchema;
    /** @deprecated use `GetBankStatementRequest$Outbound` instead. */
    export type Outbound = GetBankStatementRequest$Outbound;
}

/** @internal */
export const GetBankStatementResponse$inboundSchema: z.ZodType<
    GetBankStatementResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        classes: z.array(shared.BankStatement$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetBankStatementResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    classes?: Array<shared.BankStatement$Outbound> | undefined;
};

/** @internal */
export const GetBankStatementResponse$outboundSchema: z.ZodType<
    GetBankStatementResponse$Outbound,
    z.ZodTypeDef,
    GetBankStatementResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        classes: z.array(shared.BankStatement$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBankStatementResponse$ {
    /** @deprecated use `GetBankStatementResponse$inboundSchema` instead. */
    export const inboundSchema = GetBankStatementResponse$inboundSchema;
    /** @deprecated use `GetBankStatementResponse$outboundSchema` instead. */
    export const outboundSchema = GetBankStatementResponse$outboundSchema;
    /** @deprecated use `GetBankStatementResponse$Outbound` instead. */
    export type Outbound = GetBankStatementResponse$Outbound;
}
