/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type GetCustomFieldRequest = {
    /**
     * Unique identifier
     */
    id: string;
};

export type GetCustomFieldResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Custom fields that are set on resource
     */
    customField?: shared.CustomField | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const GetCustomFieldRequest$inboundSchema: z.ZodType<
    GetCustomFieldRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string(),
});

/** @internal */
export type GetCustomFieldRequest$Outbound = {
    id: string;
};

/** @internal */
export const GetCustomFieldRequest$outboundSchema: z.ZodType<
    GetCustomFieldRequest$Outbound,
    z.ZodTypeDef,
    GetCustomFieldRequest
> = z.object({
    id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomFieldRequest$ {
    /** @deprecated use `GetCustomFieldRequest$inboundSchema` instead. */
    export const inboundSchema = GetCustomFieldRequest$inboundSchema;
    /** @deprecated use `GetCustomFieldRequest$outboundSchema` instead. */
    export const outboundSchema = GetCustomFieldRequest$outboundSchema;
    /** @deprecated use `GetCustomFieldRequest$Outbound` instead. */
    export type Outbound = GetCustomFieldRequest$Outbound;
}

/** @internal */
export const GetCustomFieldResponse$inboundSchema: z.ZodType<
    GetCustomFieldResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        CustomField: shared.CustomField$inboundSchema.optional(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            CustomField: "customField",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetCustomFieldResponse$Outbound = {
    ContentType: string;
    CustomField?: shared.CustomField$Outbound | undefined;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const GetCustomFieldResponse$outboundSchema: z.ZodType<
    GetCustomFieldResponse$Outbound,
    z.ZodTypeDef,
    GetCustomFieldResponse
> = z
    .object({
        contentType: z.string(),
        customField: shared.CustomField$outboundSchema.optional(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            customField: "CustomField",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomFieldResponse$ {
    /** @deprecated use `GetCustomFieldResponse$inboundSchema` instead. */
    export const inboundSchema = GetCustomFieldResponse$inboundSchema;
    /** @deprecated use `GetCustomFieldResponse$outboundSchema` instead. */
    export const outboundSchema = GetCustomFieldResponse$outboundSchema;
    /** @deprecated use `GetCustomFieldResponse$Outbound` instead. */
    export type Outbound = GetCustomFieldResponse$Outbound;
}
