/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type GetCalculation1099BatchItemRequest = {
    /**
     * Unique identifier for a batch
     */
    batchId: string;
    /**
     * Unique identifier for an item in a batch
     */
    batchItemId: string;
};

export type GetCalculation1099BatchItemResponse = {
    /**
     * An item that will be converted into a calculation 1099
     */
    bulkCalculation1099Item?: shared.BulkCalculation1099Item | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const GetCalculation1099BatchItemRequest$inboundSchema: z.ZodType<
    GetCalculation1099BatchItemRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    batchId: z.string(),
    batchItemId: z.string(),
});

/** @internal */
export type GetCalculation1099BatchItemRequest$Outbound = {
    batchId: string;
    batchItemId: string;
};

/** @internal */
export const GetCalculation1099BatchItemRequest$outboundSchema: z.ZodType<
    GetCalculation1099BatchItemRequest$Outbound,
    z.ZodTypeDef,
    GetCalculation1099BatchItemRequest
> = z.object({
    batchId: z.string(),
    batchItemId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCalculation1099BatchItemRequest$ {
    /** @deprecated use `GetCalculation1099BatchItemRequest$inboundSchema` instead. */
    export const inboundSchema = GetCalculation1099BatchItemRequest$inboundSchema;
    /** @deprecated use `GetCalculation1099BatchItemRequest$outboundSchema` instead. */
    export const outboundSchema = GetCalculation1099BatchItemRequest$outboundSchema;
    /** @deprecated use `GetCalculation1099BatchItemRequest$Outbound` instead. */
    export type Outbound = GetCalculation1099BatchItemRequest$Outbound;
}

/** @internal */
export const GetCalculation1099BatchItemResponse$inboundSchema: z.ZodType<
    GetCalculation1099BatchItemResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        BulkCalculation1099Item: shared.BulkCalculation1099Item$inboundSchema.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            BulkCalculation1099Item: "bulkCalculation1099Item",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetCalculation1099BatchItemResponse$Outbound = {
    BulkCalculation1099Item?: shared.BulkCalculation1099Item$Outbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const GetCalculation1099BatchItemResponse$outboundSchema: z.ZodType<
    GetCalculation1099BatchItemResponse$Outbound,
    z.ZodTypeDef,
    GetCalculation1099BatchItemResponse
> = z
    .object({
        bulkCalculation1099Item: shared.BulkCalculation1099Item$outboundSchema.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            bulkCalculation1099Item: "BulkCalculation1099Item",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCalculation1099BatchItemResponse$ {
    /** @deprecated use `GetCalculation1099BatchItemResponse$inboundSchema` instead. */
    export const inboundSchema = GetCalculation1099BatchItemResponse$inboundSchema;
    /** @deprecated use `GetCalculation1099BatchItemResponse$outboundSchema` instead. */
    export const outboundSchema = GetCalculation1099BatchItemResponse$outboundSchema;
    /** @deprecated use `GetCalculation1099BatchItemResponse$Outbound` instead. */
    export type Outbound = GetCalculation1099BatchItemResponse$Outbound;
}
