/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type GetPayableBatchItemRequest = {
    /**
     * Unique identifier for a batch
     */
    batchId: string;
};

export type GetPayableBatchItemResponse = {
    /**
     * Summary of the bulk payable import
     */
    bulkPayableImportSummary?: shared.BulkPayableImportSummary | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export const GetPayableBatchItemRequest$inboundSchema: z.ZodType<
    GetPayableBatchItemRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    batchId: z.string(),
});

/** @internal */
export type GetPayableBatchItemRequest$Outbound = {
    batchId: string;
};

/** @internal */
export const GetPayableBatchItemRequest$outboundSchema: z.ZodType<
    GetPayableBatchItemRequest$Outbound,
    z.ZodTypeDef,
    GetPayableBatchItemRequest
> = z.object({
    batchId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPayableBatchItemRequest$ {
    /** @deprecated use `GetPayableBatchItemRequest$inboundSchema` instead. */
    export const inboundSchema = GetPayableBatchItemRequest$inboundSchema;
    /** @deprecated use `GetPayableBatchItemRequest$outboundSchema` instead. */
    export const outboundSchema = GetPayableBatchItemRequest$outboundSchema;
    /** @deprecated use `GetPayableBatchItemRequest$Outbound` instead. */
    export type Outbound = GetPayableBatchItemRequest$Outbound;
}

/** @internal */
export const GetPayableBatchItemResponse$inboundSchema: z.ZodType<
    GetPayableBatchItemResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        BulkPayableImportSummary: shared.BulkPayableImportSummary$inboundSchema.optional(),
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
    })
    .transform((v) => {
        return remap$(v, {
            BulkPayableImportSummary: "bulkPayableImportSummary",
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type GetPayableBatchItemResponse$Outbound = {
    BulkPayableImportSummary?: shared.BulkPayableImportSummary$Outbound | undefined;
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
};

/** @internal */
export const GetPayableBatchItemResponse$outboundSchema: z.ZodType<
    GetPayableBatchItemResponse$Outbound,
    z.ZodTypeDef,
    GetPayableBatchItemResponse
> = z
    .object({
        bulkPayableImportSummary: shared.BulkPayableImportSummary$outboundSchema.optional(),
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
    })
    .transform((v) => {
        return remap$(v, {
            bulkPayableImportSummary: "BulkPayableImportSummary",
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPayableBatchItemResponse$ {
    /** @deprecated use `GetPayableBatchItemResponse$inboundSchema` instead. */
    export const inboundSchema = GetPayableBatchItemResponse$inboundSchema;
    /** @deprecated use `GetPayableBatchItemResponse$outboundSchema` instead. */
    export const outboundSchema = GetPayableBatchItemResponse$outboundSchema;
    /** @deprecated use `GetPayableBatchItemResponse$Outbound` instead. */
    export type Outbound = GetPayableBatchItemResponse$Outbound;
}
