/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListMemberClientAssociationsResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * A list of memberClient objects
   */
  classes?: Array<shared.MemberClientSchema> | undefined;
};

/** @internal */
export const ListMemberClientAssociationsResponse$inboundSchema: z.ZodType<
  ListMemberClientAssociationsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  classes: z.array(shared.MemberClientSchema$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type ListMemberClientAssociationsResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
  classes?: Array<shared.MemberClientSchema$Outbound> | undefined;
};

/** @internal */
export const ListMemberClientAssociationsResponse$outboundSchema: z.ZodType<
  ListMemberClientAssociationsResponse$Outbound,
  z.ZodTypeDef,
  ListMemberClientAssociationsResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
  classes: z.array(shared.MemberClientSchema$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMemberClientAssociationsResponse$ {
  /** @deprecated use `ListMemberClientAssociationsResponse$inboundSchema` instead. */
  export const inboundSchema =
    ListMemberClientAssociationsResponse$inboundSchema;
  /** @deprecated use `ListMemberClientAssociationsResponse$outboundSchema` instead. */
  export const outboundSchema =
    ListMemberClientAssociationsResponse$outboundSchema;
  /** @deprecated use `ListMemberClientAssociationsResponse$Outbound` instead. */
  export type Outbound = ListMemberClientAssociationsResponse$Outbound;
}

export function listMemberClientAssociationsResponseToJSON(
  listMemberClientAssociationsResponse: ListMemberClientAssociationsResponse,
): string {
  return JSON.stringify(
    ListMemberClientAssociationsResponse$outboundSchema.parse(
      listMemberClientAssociationsResponse,
    ),
  );
}

export function listMemberClientAssociationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMemberClientAssociationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListMemberClientAssociationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMemberClientAssociationsResponse' from JSON`,
  );
}
