/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";
import * as z from "zod";

export type ListRegisteredCollaboratorsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     *  A list of collaborators
     */
    classes?: Array<shared.CollaboratorSchema> | undefined;
};

/** @internal */
export const ListRegisteredCollaboratorsResponse$inboundSchema: z.ZodType<
    ListRegisteredCollaboratorsResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        ContentType: z.string(),
        StatusCode: z.number().int(),
        RawResponse: z.instanceof(Response),
        classes: z.array(shared.CollaboratorSchema$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            ContentType: "contentType",
            StatusCode: "statusCode",
            RawResponse: "rawResponse",
        });
    });

/** @internal */
export type ListRegisteredCollaboratorsResponse$Outbound = {
    ContentType: string;
    StatusCode: number;
    RawResponse: never;
    classes?: Array<shared.CollaboratorSchema$Outbound> | undefined;
};

/** @internal */
export const ListRegisteredCollaboratorsResponse$outboundSchema: z.ZodType<
    ListRegisteredCollaboratorsResponse$Outbound,
    z.ZodTypeDef,
    ListRegisteredCollaboratorsResponse
> = z
    .object({
        contentType: z.string(),
        statusCode: z.number().int(),
        rawResponse: z.instanceof(Response).transform(() => {
            throw new Error("Response cannot be serialized");
        }),
        classes: z.array(shared.CollaboratorSchema$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            contentType: "ContentType",
            statusCode: "StatusCode",
            rawResponse: "RawResponse",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListRegisteredCollaboratorsResponse$ {
    /** @deprecated use `ListRegisteredCollaboratorsResponse$inboundSchema` instead. */
    export const inboundSchema = ListRegisteredCollaboratorsResponse$inboundSchema;
    /** @deprecated use `ListRegisteredCollaboratorsResponse$outboundSchema` instead. */
    export const outboundSchema = ListRegisteredCollaboratorsResponse$outboundSchema;
    /** @deprecated use `ListRegisteredCollaboratorsResponse$Outbound` instead. */
    export type Outbound = ListRegisteredCollaboratorsResponse$Outbound;
}
