/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import { z } from "zod";

export type GetUsersAuthorizedScopeGroupsRequestingUserIdRequest = {
    /**
     * Requesting User Id
     */
    requestingUserId: string;
};

export type GetUsersAuthorizedScopeGroupsRequestingUserIdResponse = {
    /**
     * Authorized scopes on member
     */
    authorizationScopes?: shared.AuthorizationScopes | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetUsersAuthorizedScopeGroupsRequestingUserIdRequest$ {
    export type Inbound = {
        requestingUserId: string;
    };

    export const inboundSchema: z.ZodType<
        GetUsersAuthorizedScopeGroupsRequestingUserIdRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            requestingUserId: z.string(),
        })
        .transform((v) => {
            return {
                requestingUserId: v.requestingUserId,
            };
        });

    export type Outbound = {
        requestingUserId: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetUsersAuthorizedScopeGroupsRequestingUserIdRequest
    > = z
        .object({
            requestingUserId: z.string(),
        })
        .transform((v) => {
            return {
                requestingUserId: v.requestingUserId,
            };
        });
}

/** @internal */
export namespace GetUsersAuthorizedScopeGroupsRequestingUserIdResponse$ {
    export type Inbound = {
        AuthorizationScopes?: shared.AuthorizationScopes$.Inbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<
        GetUsersAuthorizedScopeGroupsRequestingUserIdResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            AuthorizationScopes: shared.AuthorizationScopes$.inboundSchema.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.AuthorizationScopes === undefined
                    ? null
                    : { authorizationScopes: v.AuthorizationScopes }),
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        AuthorizationScopes?: shared.AuthorizationScopes$.Outbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetUsersAuthorizedScopeGroupsRequestingUserIdResponse
    > = z
        .object({
            authorizationScopes: shared.AuthorizationScopes$.outboundSchema.optional(),
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.authorizationScopes === undefined
                    ? null
                    : { AuthorizationScopes: v.authorizationScopes }),
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
