/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type PatchUsersUserClientIdRequest = {
    clientUpdateRequest?: shared.ClientUpdateRequest | undefined;
    /**
     * Unique identifier
     */
    id: string;
};

export type PatchUsersUserClientIdResponse = {
    /**
     * A client
     */
    clientResponse?: shared.ClientResponse | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace PatchUsersUserClientIdRequest$ {
    export type Inbound = {
        ClientUpdateRequest?: shared.ClientUpdateRequest$.Inbound | undefined;
        id: string;
    };

    export const inboundSchema: z.ZodType<PatchUsersUserClientIdRequest, z.ZodTypeDef, Inbound> = z
        .object({
            ClientUpdateRequest: shared.ClientUpdateRequest$.inboundSchema.optional(),
            id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.ClientUpdateRequest === undefined
                    ? null
                    : { clientUpdateRequest: v.ClientUpdateRequest }),
                id: v.id,
            };
        });

    export type Outbound = {
        ClientUpdateRequest?: shared.ClientUpdateRequest$.Outbound | undefined;
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PatchUsersUserClientIdRequest> =
        z
            .object({
                clientUpdateRequest: shared.ClientUpdateRequest$.outboundSchema.optional(),
                id: z.string(),
            })
            .transform((v) => {
                return {
                    ...(v.clientUpdateRequest === undefined
                        ? null
                        : { ClientUpdateRequest: v.clientUpdateRequest }),
                    id: v.id,
                };
            });
}

/** @internal */
export namespace PatchUsersUserClientIdResponse$ {
    export type Inbound = {
        ClientResponse?: shared.ClientResponse$.Inbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<PatchUsersUserClientIdResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ClientResponse: shared.ClientResponse$.inboundSchema.optional(),
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.ClientResponse === undefined ? null : { clientResponse: v.ClientResponse }),
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ClientResponse?: shared.ClientResponse$.Outbound | undefined;
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PatchUsersUserClientIdResponse> =
        z
            .object({
                clientResponse: shared.ClientResponse$.outboundSchema.optional(),
                contentType: z.string(),
                statusCode: z.number().int(),
                rawResponse: z.instanceof(Response).transform(() => {
                    throw new Error("Response cannot be serialized");
                }),
            })
            .transform((v) => {
                return {
                    ...(v.clientResponse === undefined
                        ? null
                        : { ClientResponse: v.clientResponse }),
                    ContentType: v.contentType,
                    StatusCode: v.statusCode,
                    RawResponse: v.rawResponse,
                };
            });
}
