/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type PatchUsersUserMemberIdRequest = {
    memberUpdateRequest?: shared.MemberUpdateRequest | undefined;
    /**
     * Unique identifier
     */
    id: string;
};

export type PatchUsersUserMemberIdResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Member object
     */
    member?: shared.Member | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace PatchUsersUserMemberIdRequest$ {
    export type Inbound = {
        MemberUpdateRequest?: shared.MemberUpdateRequest$.Inbound | undefined;
        id: string;
    };

    export const inboundSchema: z.ZodType<PatchUsersUserMemberIdRequest, z.ZodTypeDef, Inbound> = z
        .object({
            MemberUpdateRequest: shared.MemberUpdateRequest$.inboundSchema.optional(),
            id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.MemberUpdateRequest === undefined
                    ? null
                    : { memberUpdateRequest: v.MemberUpdateRequest }),
                id: v.id,
            };
        });

    export type Outbound = {
        MemberUpdateRequest?: shared.MemberUpdateRequest$.Outbound | undefined;
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PatchUsersUserMemberIdRequest> =
        z
            .object({
                memberUpdateRequest: shared.MemberUpdateRequest$.outboundSchema.optional(),
                id: z.string(),
            })
            .transform((v) => {
                return {
                    ...(v.memberUpdateRequest === undefined
                        ? null
                        : { MemberUpdateRequest: v.memberUpdateRequest }),
                    id: v.id,
                };
            });
}

/** @internal */
export namespace PatchUsersUserMemberIdResponse$ {
    export type Inbound = {
        ContentType: string;
        Member?: shared.Member$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<PatchUsersUserMemberIdResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            Member: shared.Member$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.Member === undefined ? null : { member: v.Member }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        Member?: shared.Member$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PatchUsersUserMemberIdResponse> =
        z
            .object({
                contentType: z.string(),
                member: shared.Member$.outboundSchema.optional(),
                statusCode: z.number().int(),
                rawResponse: z.instanceof(Response).transform(() => {
                    throw new Error("Response cannot be serialized");
                }),
            })
            .transform((v) => {
                return {
                    ContentType: v.contentType,
                    ...(v.member === undefined ? null : { Member: v.member }),
                    StatusCode: v.statusCode,
                    RawResponse: v.rawResponse,
                };
            });
}
