/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ServiceEnablementUpdate = {
    enabled: boolean;
};

/** @internal */
export namespace ServiceEnablementUpdate$ {
    export type Inbound = {
        enabled: boolean;
    };

    export const inboundSchema: z.ZodType<ServiceEnablementUpdate, z.ZodTypeDef, Inbound> = z
        .object({
            enabled: z.boolean(),
        })
        .transform((v) => {
            return {
                enabled: v.enabled,
            };
        });

    export type Outbound = {
        enabled: boolean;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ServiceEnablementUpdate> = z
        .object({
            enabled: z.boolean(),
        })
        .transform((v) => {
            return {
                enabled: v.enabled,
            };
        });
}
