/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Address extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "addressLine1" })
    addressLine1: string;

    @SpeakeasyMetadata()
    @Expose({ name: "addressLine2" })
    addressLine2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "postalCode" })
    postalCode: string;

    @SpeakeasyMetadata()
    @Expose({ name: "state" })
    state: string;
}
