/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    MemberClientForm1099Balances,
    MemberClientForm1099Balances$,
} from "./memberclientform1099balances";
import { z } from "zod";

export type B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c = {
    twoThousandAndTwentyOne?: MemberClientForm1099Balances | null | undefined;
    twoThousandAndTwentyTwo?: MemberClientForm1099Balances | null | undefined;
};

/** @internal */
export namespace B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c$ {
    export type Inbound = {
        "2021"?: MemberClientForm1099Balances$.Inbound | null | undefined;
        "2022"?: MemberClientForm1099Balances$.Inbound | null | undefined;
    };

    export const inboundSchema: z.ZodType<
        B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            "2021": z.nullable(MemberClientForm1099Balances$.inboundSchema).optional(),
            "2022": z.nullable(MemberClientForm1099Balances$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v["2021"] === undefined ? null : { twoThousandAndTwentyOne: v["2021"] }),
                ...(v["2022"] === undefined ? null : { twoThousandAndTwentyTwo: v["2022"] }),
            };
        });

    export type Outbound = {
        "2021"?: MemberClientForm1099Balances$.Outbound | null | undefined;
        "2022"?: MemberClientForm1099Balances$.Outbound | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        B9789f45f8c8070ff38a64d80c2e4a8732ddaf329e46546474400d26f84c0f1c
    > = z
        .object({
            twoThousandAndTwentyOne: z
                .nullable(MemberClientForm1099Balances$.outboundSchema)
                .optional(),
            twoThousandAndTwentyTwo: z
                .nullable(MemberClientForm1099Balances$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.twoThousandAndTwentyOne === undefined
                    ? null
                    : { "2021": v.twoThousandAndTwentyOne }),
                ...(v.twoThousandAndTwentyTwo === undefined
                    ? null
                    : { "2022": v.twoThousandAndTwentyTwo }),
            };
        });
}
