/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import {
    RedactedMember,
    RedactedMember$inboundSchema,
    RedactedMember$Outbound,
    RedactedMember$outboundSchema,
} from "./redactedmember.js";
import {
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2,
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$inboundSchema,
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$Outbound,
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$outboundSchema,
} from "./sevenhundredandfiftysevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2.js";
import {
    UserRoles,
    UserRoles$inboundSchema,
    UserRoles$Outbound,
    UserRoles$outboundSchema,
} from "./userroles.js";
import * as z from "zod";

export const BulkCollaboratorBatchStatus = {
    Open: "Open",
    Pending: "Pending",
    Processing: "Processing",
    Complete: "Complete",
    Failed: "Failed",
} as const;
export type BulkCollaboratorBatchStatus = ClosedEnum<typeof BulkCollaboratorBatchStatus>;

export type BulkCollaboratorBatch = {
    bulkCollaboratorBatchId: string;
    client: RedactedMember;
    clientId: string;
    createdAt: string;
    eventActors: { [k: string]: string };
    labels: { [k: string]: string };
    statistics?:
        | SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2
        | null
        | undefined;
    status: BulkCollaboratorBatchStatus;
    updatedAt: string;
    userRoles: UserRoles;
};

/** @internal */
export const BulkCollaboratorBatchStatus$inboundSchema: z.ZodNativeEnum<
    typeof BulkCollaboratorBatchStatus
> = z.nativeEnum(BulkCollaboratorBatchStatus);

/** @internal */
export const BulkCollaboratorBatchStatus$outboundSchema: z.ZodNativeEnum<
    typeof BulkCollaboratorBatchStatus
> = BulkCollaboratorBatchStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkCollaboratorBatchStatus$ {
    /** @deprecated use `BulkCollaboratorBatchStatus$inboundSchema` instead. */
    export const inboundSchema = BulkCollaboratorBatchStatus$inboundSchema;
    /** @deprecated use `BulkCollaboratorBatchStatus$outboundSchema` instead. */
    export const outboundSchema = BulkCollaboratorBatchStatus$outboundSchema;
}

/** @internal */
export const BulkCollaboratorBatch$inboundSchema: z.ZodType<
    BulkCollaboratorBatch,
    z.ZodTypeDef,
    unknown
> = z.object({
    bulkCollaboratorBatchId: z.string(),
    client: RedactedMember$inboundSchema,
    clientId: z.string(),
    createdAt: z.string(),
    eventActors: z.record(z.string()),
    labels: z.record(z.string()),
    statistics: z
        .nullable(
            SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$inboundSchema
        )
        .optional(),
    status: BulkCollaboratorBatchStatus$inboundSchema,
    updatedAt: z.string(),
    userRoles: UserRoles$inboundSchema,
});

/** @internal */
export type BulkCollaboratorBatch$Outbound = {
    bulkCollaboratorBatchId: string;
    client: RedactedMember$Outbound;
    clientId: string;
    createdAt: string;
    eventActors: { [k: string]: string };
    labels: { [k: string]: string };
    statistics?:
        | SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$Outbound
        | null
        | undefined;
    status: string;
    updatedAt: string;
    userRoles: UserRoles$Outbound;
};

/** @internal */
export const BulkCollaboratorBatch$outboundSchema: z.ZodType<
    BulkCollaboratorBatch$Outbound,
    z.ZodTypeDef,
    BulkCollaboratorBatch
> = z.object({
    bulkCollaboratorBatchId: z.string(),
    client: RedactedMember$outboundSchema,
    clientId: z.string(),
    createdAt: z.string(),
    eventActors: z.record(z.string()),
    labels: z.record(z.string()),
    statistics: z
        .nullable(
            SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$outboundSchema
        )
        .optional(),
    status: BulkCollaboratorBatchStatus$outboundSchema,
    updatedAt: z.string(),
    userRoles: UserRoles$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BulkCollaboratorBatch$ {
    /** @deprecated use `BulkCollaboratorBatch$inboundSchema` instead. */
    export const inboundSchema = BulkCollaboratorBatch$inboundSchema;
    /** @deprecated use `BulkCollaboratorBatch$outboundSchema` instead. */
    export const outboundSchema = BulkCollaboratorBatch$outboundSchema;
    /** @deprecated use `BulkCollaboratorBatch$Outbound` instead. */
    export type Outbound = BulkCollaboratorBatch$Outbound;
}
