/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { RedactedMember, RedactedMember$ } from "./redactedmember";
import {
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2,
    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$,
} from "./sevenhundredandfiftysevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2";
import { UserRoles, UserRoles$ } from "./userroles";
import { z } from "zod";

export enum BulkCollaboratorBatchStatus {
    Open = "Open",
    Pending = "Pending",
    Processing = "Processing",
    Complete = "Complete",
    Failed = "Failed",
}

export type BulkCollaboratorBatch = {
    bulkCollaboratorBatchId: string;
    client: RedactedMember;
    clientId: string;
    createdAt: string;
    eventActors: Record<string, string>;
    labels: Record<string, string>;
    statistics?:
        | SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2
        | null
        | undefined;
    status: BulkCollaboratorBatchStatus;
    updatedAt: string;
    userRoles: UserRoles;
};

/** @internal */
export const BulkCollaboratorBatchStatus$ = z.nativeEnum(BulkCollaboratorBatchStatus);

/** @internal */
export namespace BulkCollaboratorBatch$ {
    export type Inbound = {
        bulkCollaboratorBatchId: string;
        client: RedactedMember$.Inbound;
        clientId: string;
        createdAt: string;
        eventActors: Record<string, string>;
        labels: Record<string, string>;
        statistics?:
            | SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$.Inbound
            | null
            | undefined;
        status: BulkCollaboratorBatchStatus;
        updatedAt: string;
        userRoles: UserRoles$.Inbound;
    };

    export const inboundSchema: z.ZodType<BulkCollaboratorBatch, z.ZodTypeDef, Inbound> = z
        .object({
            bulkCollaboratorBatchId: z.string(),
            client: RedactedMember$.inboundSchema,
            clientId: z.string(),
            createdAt: z.string(),
            eventActors: z.record(z.string()),
            labels: z.record(z.string()),
            statistics: z
                .nullable(
                    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$.inboundSchema
                )
                .optional(),
            status: BulkCollaboratorBatchStatus$,
            updatedAt: z.string(),
            userRoles: UserRoles$.inboundSchema,
        })
        .transform((v) => {
            return {
                bulkCollaboratorBatchId: v.bulkCollaboratorBatchId,
                client: v.client,
                clientId: v.clientId,
                createdAt: v.createdAt,
                eventActors: v.eventActors,
                labels: v.labels,
                ...(v.statistics === undefined ? null : { statistics: v.statistics }),
                status: v.status,
                updatedAt: v.updatedAt,
                userRoles: v.userRoles,
            };
        });

    export type Outbound = {
        bulkCollaboratorBatchId: string;
        client: RedactedMember$.Outbound;
        clientId: string;
        createdAt: string;
        eventActors: Record<string, string>;
        labels: Record<string, string>;
        statistics?:
            | SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$.Outbound
            | null
            | undefined;
        status: BulkCollaboratorBatchStatus;
        updatedAt: string;
        userRoles: UserRoles$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, BulkCollaboratorBatch> = z
        .object({
            bulkCollaboratorBatchId: z.string(),
            client: RedactedMember$.outboundSchema,
            clientId: z.string(),
            createdAt: z.string(),
            eventActors: z.record(z.string()),
            labels: z.record(z.string()),
            statistics: z
                .nullable(
                    SevenHundredAndFiftySevenf4961b94334fd41cedc27262be7b14583377703cda6490b996969bd4e66c2$.outboundSchema
                )
                .optional(),
            status: BulkCollaboratorBatchStatus$,
            updatedAt: z.string(),
            userRoles: UserRoles$.outboundSchema,
        })
        .transform((v) => {
            return {
                bulkCollaboratorBatchId: v.bulkCollaboratorBatchId,
                client: v.client,
                clientId: v.clientId,
                createdAt: v.createdAt,
                eventActors: v.eventActors,
                labels: v.labels,
                ...(v.statistics === undefined ? null : { statistics: v.statistics }),
                status: v.status,
                updatedAt: v.updatedAt,
                userRoles: v.userRoles,
            };
        });
}
