/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import {
  B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a,
  B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$inboundSchema,
  B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$Outbound,
  B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$outboundSchema,
} from "./b22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a.js";
import {
  CollaboratorEvents,
  CollaboratorEvents$inboundSchema,
  CollaboratorEvents$Outbound,
  CollaboratorEvents$outboundSchema,
} from "./collaboratorevents.js";
import {
  RedactedMember,
  RedactedMember$inboundSchema,
  RedactedMember$Outbound,
  RedactedMember$outboundSchema,
} from "./redactedmember.js";
import {
  SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d,
  SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$inboundSchema,
  SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$Outbound,
  SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$outboundSchema,
} from "./sixtysixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d.js";

export type CollaboratorsReportResponseLabels = {};

export const CollaboratorsReportResponseStatus = {
  Active: "Active",
  Inactive: "Inactive",
  Pending: "Pending",
} as const;
export type CollaboratorsReportResponseStatus = ClosedEnum<
  typeof CollaboratorsReportResponseStatus
>;

export const CollaboratorsReportResponseTaxStatus = {
  Complete: "Complete",
  Failed: "Failed",
  Pending: "Pending",
  Incomplete: "Incomplete",
} as const;
export type CollaboratorsReportResponseTaxStatus = ClosedEnum<
  typeof CollaboratorsReportResponseTaxStatus
>;

export type CollaboratorsReportResponse = {
  clientId: string;
  collaboratorGroups: Array<
    SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d
  >;
  createdAt: string;
  externalId?: string | null | undefined;
  inviteEmail: string;
  labels?: CollaboratorsReportResponseLabels | null | undefined;
  member: RedactedMember;
  memberClientId: string;
  memberEvents?: CollaboratorEvents | null | undefined;
  memberId: string;
  servicesStatus:
    B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a;
  status: CollaboratorsReportResponseStatus;
  taxDocumentStared?: boolean | null | undefined;
  taxStatus: CollaboratorsReportResponseTaxStatus;
  updatedAt: string;
};

/** @internal */
export const CollaboratorsReportResponseLabels$inboundSchema: z.ZodType<
  CollaboratorsReportResponseLabels,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type CollaboratorsReportResponseLabels$Outbound = {};

/** @internal */
export const CollaboratorsReportResponseLabels$outboundSchema: z.ZodType<
  CollaboratorsReportResponseLabels$Outbound,
  z.ZodTypeDef,
  CollaboratorsReportResponseLabels
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollaboratorsReportResponseLabels$ {
  /** @deprecated use `CollaboratorsReportResponseLabels$inboundSchema` instead. */
  export const inboundSchema = CollaboratorsReportResponseLabels$inboundSchema;
  /** @deprecated use `CollaboratorsReportResponseLabels$outboundSchema` instead. */
  export const outboundSchema =
    CollaboratorsReportResponseLabels$outboundSchema;
  /** @deprecated use `CollaboratorsReportResponseLabels$Outbound` instead. */
  export type Outbound = CollaboratorsReportResponseLabels$Outbound;
}

/** @internal */
export const CollaboratorsReportResponseStatus$inboundSchema: z.ZodNativeEnum<
  typeof CollaboratorsReportResponseStatus
> = z.nativeEnum(CollaboratorsReportResponseStatus);

/** @internal */
export const CollaboratorsReportResponseStatus$outboundSchema: z.ZodNativeEnum<
  typeof CollaboratorsReportResponseStatus
> = CollaboratorsReportResponseStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollaboratorsReportResponseStatus$ {
  /** @deprecated use `CollaboratorsReportResponseStatus$inboundSchema` instead. */
  export const inboundSchema = CollaboratorsReportResponseStatus$inboundSchema;
  /** @deprecated use `CollaboratorsReportResponseStatus$outboundSchema` instead. */
  export const outboundSchema =
    CollaboratorsReportResponseStatus$outboundSchema;
}

/** @internal */
export const CollaboratorsReportResponseTaxStatus$inboundSchema:
  z.ZodNativeEnum<typeof CollaboratorsReportResponseTaxStatus> = z.nativeEnum(
    CollaboratorsReportResponseTaxStatus,
  );

/** @internal */
export const CollaboratorsReportResponseTaxStatus$outboundSchema:
  z.ZodNativeEnum<typeof CollaboratorsReportResponseTaxStatus> =
    CollaboratorsReportResponseTaxStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollaboratorsReportResponseTaxStatus$ {
  /** @deprecated use `CollaboratorsReportResponseTaxStatus$inboundSchema` instead. */
  export const inboundSchema =
    CollaboratorsReportResponseTaxStatus$inboundSchema;
  /** @deprecated use `CollaboratorsReportResponseTaxStatus$outboundSchema` instead. */
  export const outboundSchema =
    CollaboratorsReportResponseTaxStatus$outboundSchema;
}

/** @internal */
export const CollaboratorsReportResponse$inboundSchema: z.ZodType<
  CollaboratorsReportResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientId: z.string(),
  collaboratorGroups: z.array(
    SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$inboundSchema,
  ),
  createdAt: z.string(),
  externalId: z.nullable(z.string()).optional(),
  inviteEmail: z.string(),
  labels: z.nullable(
    z.lazy(() => CollaboratorsReportResponseLabels$inboundSchema),
  ).optional(),
  member: RedactedMember$inboundSchema,
  memberClientId: z.string(),
  memberEvents: z.nullable(CollaboratorEvents$inboundSchema).optional(),
  memberId: z.string(),
  servicesStatus:
    B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$inboundSchema,
  status: CollaboratorsReportResponseStatus$inboundSchema,
  taxDocumentStared: z.nullable(z.boolean()).optional(),
  taxStatus: CollaboratorsReportResponseTaxStatus$inboundSchema,
  updatedAt: z.string(),
});

/** @internal */
export type CollaboratorsReportResponse$Outbound = {
  clientId: string;
  collaboratorGroups: Array<
    SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$Outbound
  >;
  createdAt: string;
  externalId?: string | null | undefined;
  inviteEmail: string;
  labels?: CollaboratorsReportResponseLabels$Outbound | null | undefined;
  member: RedactedMember$Outbound;
  memberClientId: string;
  memberEvents?: CollaboratorEvents$Outbound | null | undefined;
  memberId: string;
  servicesStatus:
    B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$Outbound;
  status: string;
  taxDocumentStared?: boolean | null | undefined;
  taxStatus: string;
  updatedAt: string;
};

/** @internal */
export const CollaboratorsReportResponse$outboundSchema: z.ZodType<
  CollaboratorsReportResponse$Outbound,
  z.ZodTypeDef,
  CollaboratorsReportResponse
> = z.object({
  clientId: z.string(),
  collaboratorGroups: z.array(
    SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d$outboundSchema,
  ),
  createdAt: z.string(),
  externalId: z.nullable(z.string()).optional(),
  inviteEmail: z.string(),
  labels: z.nullable(
    z.lazy(() => CollaboratorsReportResponseLabels$outboundSchema),
  ).optional(),
  member: RedactedMember$outboundSchema,
  memberClientId: z.string(),
  memberEvents: z.nullable(CollaboratorEvents$outboundSchema).optional(),
  memberId: z.string(),
  servicesStatus:
    B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a$outboundSchema,
  status: CollaboratorsReportResponseStatus$outboundSchema,
  taxDocumentStared: z.nullable(z.boolean()).optional(),
  taxStatus: CollaboratorsReportResponseTaxStatus$outboundSchema,
  updatedAt: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CollaboratorsReportResponse$ {
  /** @deprecated use `CollaboratorsReportResponse$inboundSchema` instead. */
  export const inboundSchema = CollaboratorsReportResponse$inboundSchema;
  /** @deprecated use `CollaboratorsReportResponse$outboundSchema` instead. */
  export const outboundSchema = CollaboratorsReportResponse$outboundSchema;
  /** @deprecated use `CollaboratorsReportResponse$Outbound` instead. */
  export type Outbound = CollaboratorsReportResponse$Outbound;
}
