/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a } from "./b22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a";
import { CollaboratorEvents } from "./collaboratorevents";
import { CollaboratorPayoutsSummary } from "./collaboratorpayoutssummary";
import { RedactedMember } from "./redactedmember";
import { SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d } from "./sixtysixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d";
import { Expose, Type } from "class-transformer";

export class Labels extends SpeakeasyBase {}

export enum CollaboratorsPayoutsSummaryReportResponseStatus {
    Active = "Active",
    Inactive = "Inactive",
    Pending = "Pending",
}

export enum CollaboratorsPayoutsSummaryReportResponseTaxStatus {
    Complete = "Complete",
    Failed = "Failed",
    Pending = "Pending",
    Incomplete = "Incomplete",
}

export class CollaboratorsPayoutsSummaryReportResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "clientId" })
    clientId: string;

    @SpeakeasyMetadata({
        elemType: SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d,
    })
    @Expose({ name: "collaboratorGroups" })
    @Type(() => SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d)
    collaboratorGroups: SixtySixad6f986038e3285c36e0faa5c61b52a02882d1460acb116b601a30abfb6c1d[];

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "externalId" })
    externalId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "inviteEmail" })
    inviteEmail: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    @Type(() => Labels)
    labels?: Labels;

    @SpeakeasyMetadata()
    @Expose({ name: "member" })
    @Type(() => RedactedMember)
    member: RedactedMember;

    @SpeakeasyMetadata()
    @Expose({ name: "memberClientId" })
    memberClientId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "memberEvents" })
    @Type(() => CollaboratorEvents)
    memberEvents?: CollaboratorEvents;

    @SpeakeasyMetadata()
    @Expose({ name: "memberId" })
    memberId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payoutsSummary" })
    @Type(() => CollaboratorPayoutsSummary)
    payoutsSummary: CollaboratorPayoutsSummary;

    @SpeakeasyMetadata()
    @Expose({ name: "servicesStatus" })
    @Type(() => B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a)
    servicesStatus: B22a2532acff782df851c03041e55a58727ff8e8805b1738c7dcb4dd1dd2505a;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: CollaboratorsPayoutsSummaryReportResponseStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "taxDocumentStared" })
    taxDocumentStared?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "taxStatus" })
    taxStatus: CollaboratorsPayoutsSummaryReportResponseTaxStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt: string;
}
