/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Eightcf19a7bc90727398c2780566a4070199559f4723ec14c01c448dc0356efffa1 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "errorMessage" })
    errorMessage?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "resolvedCollaboratorId" })
    resolvedCollaboratorId?: string;
}
