/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const InvoiceCollaboratorCreateRequestCurrency = {
  Usd: "USD",
  Cad: "CAD",
} as const;
export type InvoiceCollaboratorCreateRequestCurrency = ClosedEnum<
  typeof InvoiceCollaboratorCreateRequestCurrency
>;

export type InvoiceCollaboratorCreateRequest = {
  amount: number;
  currency: InvoiceCollaboratorCreateRequestCurrency;
  description: string;
  memberClientId: string;
};

/** @internal */
export const InvoiceCollaboratorCreateRequestCurrency$inboundSchema:
  z.ZodNativeEnum<typeof InvoiceCollaboratorCreateRequestCurrency> = z
    .nativeEnum(InvoiceCollaboratorCreateRequestCurrency);

/** @internal */
export const InvoiceCollaboratorCreateRequestCurrency$outboundSchema:
  z.ZodNativeEnum<typeof InvoiceCollaboratorCreateRequestCurrency> =
    InvoiceCollaboratorCreateRequestCurrency$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvoiceCollaboratorCreateRequestCurrency$ {
  /** @deprecated use `InvoiceCollaboratorCreateRequestCurrency$inboundSchema` instead. */
  export const inboundSchema =
    InvoiceCollaboratorCreateRequestCurrency$inboundSchema;
  /** @deprecated use `InvoiceCollaboratorCreateRequestCurrency$outboundSchema` instead. */
  export const outboundSchema =
    InvoiceCollaboratorCreateRequestCurrency$outboundSchema;
}

/** @internal */
export const InvoiceCollaboratorCreateRequest$inboundSchema: z.ZodType<
  InvoiceCollaboratorCreateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number(),
  currency: InvoiceCollaboratorCreateRequestCurrency$inboundSchema,
  description: z.string(),
  memberClientId: z.string(),
});

/** @internal */
export type InvoiceCollaboratorCreateRequest$Outbound = {
  amount: number;
  currency: string;
  description: string;
  memberClientId: string;
};

/** @internal */
export const InvoiceCollaboratorCreateRequest$outboundSchema: z.ZodType<
  InvoiceCollaboratorCreateRequest$Outbound,
  z.ZodTypeDef,
  InvoiceCollaboratorCreateRequest
> = z.object({
  amount: z.number(),
  currency: InvoiceCollaboratorCreateRequestCurrency$outboundSchema,
  description: z.string(),
  memberClientId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InvoiceCollaboratorCreateRequest$ {
  /** @deprecated use `InvoiceCollaboratorCreateRequest$inboundSchema` instead. */
  export const inboundSchema = InvoiceCollaboratorCreateRequest$inboundSchema;
  /** @deprecated use `InvoiceCollaboratorCreateRequest$outboundSchema` instead. */
  export const outboundSchema = InvoiceCollaboratorCreateRequest$outboundSchema;
  /** @deprecated use `InvoiceCollaboratorCreateRequest$Outbound` instead. */
  export type Outbound = InvoiceCollaboratorCreateRequest$Outbound;
}
