/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { InvoiceAttachmentFile, InvoiceAttachmentFile$ } from "./invoiceattachmentfile";
import { z } from "zod";

export type InvoiceAttachments = {
    customAttachmentIds?: Array<string> | null | undefined;
    customAttachmentInfo?: Array<InvoiceAttachmentFile> | null | undefined;
    invoiceLink?: string | null | undefined;
    invoicePdf?: string | null | undefined;
    receiptPdf?: string | null | undefined;
};

/** @internal */
export namespace InvoiceAttachments$ {
    export type Inbound = {
        customAttachmentIds?: Array<string> | null | undefined;
        customAttachmentInfo?: Array<InvoiceAttachmentFile$.Inbound> | null | undefined;
        invoiceLink?: string | null | undefined;
        invoicePdf?: string | null | undefined;
        receiptPdf?: string | null | undefined;
    };

    export const inboundSchema: z.ZodType<InvoiceAttachments, z.ZodTypeDef, Inbound> = z
        .object({
            customAttachmentIds: z.nullable(z.array(z.string())).optional(),
            customAttachmentInfo: z
                .nullable(z.array(InvoiceAttachmentFile$.inboundSchema))
                .optional(),
            invoiceLink: z.nullable(z.string()).optional(),
            invoicePdf: z.nullable(z.string()).optional(),
            receiptPdf: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.customAttachmentIds === undefined
                    ? null
                    : { customAttachmentIds: v.customAttachmentIds }),
                ...(v.customAttachmentInfo === undefined
                    ? null
                    : { customAttachmentInfo: v.customAttachmentInfo }),
                ...(v.invoiceLink === undefined ? null : { invoiceLink: v.invoiceLink }),
                ...(v.invoicePdf === undefined ? null : { invoicePdf: v.invoicePdf }),
                ...(v.receiptPdf === undefined ? null : { receiptPdf: v.receiptPdf }),
            };
        });

    export type Outbound = {
        customAttachmentIds?: Array<string> | null | undefined;
        customAttachmentInfo?: Array<InvoiceAttachmentFile$.Outbound> | null | undefined;
        invoiceLink?: string | null | undefined;
        invoicePdf?: string | null | undefined;
        receiptPdf?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InvoiceAttachments> = z
        .object({
            customAttachmentIds: z.nullable(z.array(z.string())).optional(),
            customAttachmentInfo: z
                .nullable(z.array(InvoiceAttachmentFile$.outboundSchema))
                .optional(),
            invoiceLink: z.nullable(z.string()).optional(),
            invoicePdf: z.nullable(z.string()).optional(),
            receiptPdf: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.customAttachmentIds === undefined
                    ? null
                    : { customAttachmentIds: v.customAttachmentIds }),
                ...(v.customAttachmentInfo === undefined
                    ? null
                    : { customAttachmentInfo: v.customAttachmentInfo }),
                ...(v.invoiceLink === undefined ? null : { invoiceLink: v.invoiceLink }),
                ...(v.invoicePdf === undefined ? null : { invoicePdf: v.invoicePdf }),
                ...(v.receiptPdf === undefined ? null : { receiptPdf: v.receiptPdf }),
            };
        });
}
