/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { InvoiceAttachments } from "./invoiceattachments";
import { Expose, Type } from "class-transformer";

export class InvoicePdfGenerationResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "attachments" })
    @Type(() => InvoiceAttachments)
    attachments: InvoiceAttachments;

    @SpeakeasyMetadata()
    @Expose({ name: "invoiceId" })
    invoiceId: string;
}
