/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Frequency } from "./frequency";
import { Expose, Type } from "class-transformer";

export class LateFeeConfig extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "frequency" })
    @Type(() => Frequency)
    frequency: Frequency;

    @SpeakeasyMetadata()
    @Expose({ name: "lateFeeAmount" })
    lateFeeAmount?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "lateFeePercentage" })
    lateFeePercentage?: number;
}
