/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum AutoPayRequirement {
    All = "All",
    None = "None",
    LessThanNilGreaterThan = "<nil>",
}

export enum ShareTaxDocument {
    Allow = "Allow",
    Decline = "Decline",
    LessThanNilGreaterThan = "<nil>",
}

export class MemberData extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "autoPayRequirement" })
    autoPayRequirement?: AutoPayRequirement;

    @SpeakeasyMetadata()
    @Expose({ name: "externalId" })
    externalId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shareTaxDocument" })
    shareTaxDocument?: ShareTaxDocument;
}
