/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5 } from "./eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5";
import { Form1099Correction } from "./form1099correction";
import { Form1099Events } from "./form1099events";
import { Expose, Type } from "class-transformer";

export enum MemberClientForm1099BalancesDeliveryMethod {
    Electronic = "Electronic",
    Mail = "Mail",
}

export enum MemberClientForm1099BalancesExclusionReason {
    BelowThreshold = "BelowThreshold",
    CompanyStructure = "CompanyStructure",
    NonUsEntity = "NonUsEntity",
}

export enum MemberClientForm1099BalancesStatus {
    Ready = "Ready",
    NeedsActionInfo = "NeedsActionInfo",
    NeedsActionDispute = "NeedsActionDispute",
    Submitted = "Submitted",
    Rejected = "Rejected",
    Accepted = "Accepted",
    Excluded = "Excluded",
}

export class MemberClientForm1099BalancesTaxForm extends SpeakeasyBase {}

export enum MemberClientForm1099BalancesType {
    Nec = "NEC",
}

export class MemberClientForm1099Balances extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "adjustments" })
    adjustments: number;

    @SpeakeasyMetadata()
    @Expose({ name: "correction" })
    @Type(() => Form1099Correction)
    correction?: Form1099Correction;

    @SpeakeasyMetadata()
    @Expose({ name: "deliveryMethod" })
    deliveryMethod: MemberClientForm1099BalancesDeliveryMethod;

    @SpeakeasyMetadata()
    @Expose({ name: "dispute" })
    @Type(() => Eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5)
    dispute?: Eighta9c6cb49482a98cdd603ff09858cdc3e5ef6ad9807c876c4161d925a96694a5;

    @SpeakeasyMetadata()
    @Expose({ name: "events" })
    @Type(() => Form1099Events)
    events?: Form1099Events;

    @SpeakeasyMetadata()
    @Expose({ name: "exclusionReason" })
    exclusionReason: MemberClientForm1099BalancesExclusionReason;

    @SpeakeasyMetadata()
    @Expose({ name: "form1099Generated" })
    form1099Generated: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "paymentProcessingFees" })
    paymentProcessingFees: number;

    @SpeakeasyMetadata()
    @Expose({ name: "platformIncome" })
    platformIncome: number;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: MemberClientForm1099BalancesStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "taxForm" })
    @Type(() => MemberClientForm1099BalancesTaxForm)
    taxForm?: MemberClientForm1099BalancesTaxForm;

    @SpeakeasyMetadata()
    @Expose({ name: "taxFormId" })
    taxFormId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type: MemberClientForm1099BalancesType;
}
