/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    CollaboratorForm1099BalancesUpdateRequest,
    CollaboratorForm1099BalancesUpdateRequest$,
} from "./collaboratorform1099balancesupdaterequest";
import { z } from "zod";

export type Ninetyf96495b02c2509fff131505484d46479a91b7d23ed2b0f438ca117d0bccad7 = {
    twoThousandAndTwentyOne?: CollaboratorForm1099BalancesUpdateRequest | null | undefined;
    twoThousandAndTwentyTwo?: CollaboratorForm1099BalancesUpdateRequest | null | undefined;
};

/** @internal */
export namespace Ninetyf96495b02c2509fff131505484d46479a91b7d23ed2b0f438ca117d0bccad7$ {
    export type Inbound = {
        "2021"?: CollaboratorForm1099BalancesUpdateRequest$.Inbound | null | undefined;
        "2022"?: CollaboratorForm1099BalancesUpdateRequest$.Inbound | null | undefined;
    };

    export const inboundSchema: z.ZodType<
        Ninetyf96495b02c2509fff131505484d46479a91b7d23ed2b0f438ca117d0bccad7,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            "2021": z.nullable(CollaboratorForm1099BalancesUpdateRequest$.inboundSchema).optional(),
            "2022": z.nullable(CollaboratorForm1099BalancesUpdateRequest$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v["2021"] === undefined ? null : { twoThousandAndTwentyOne: v["2021"] }),
                ...(v["2022"] === undefined ? null : { twoThousandAndTwentyTwo: v["2022"] }),
            };
        });

    export type Outbound = {
        "2021"?: CollaboratorForm1099BalancesUpdateRequest$.Outbound | null | undefined;
        "2022"?: CollaboratorForm1099BalancesUpdateRequest$.Outbound | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        Ninetyf96495b02c2509fff131505484d46479a91b7d23ed2b0f438ca117d0bccad7
    > = z
        .object({
            twoThousandAndTwentyOne: z
                .nullable(CollaboratorForm1099BalancesUpdateRequest$.outboundSchema)
                .optional(),
            twoThousandAndTwentyTwo: z
                .nullable(CollaboratorForm1099BalancesUpdateRequest$.outboundSchema)
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.twoThousandAndTwentyOne === undefined
                    ? null
                    : { "2021": v.twoThousandAndTwentyOne }),
                ...(v.twoThousandAndTwentyTwo === undefined
                    ? null
                    : { "2022": v.twoThousandAndTwentyTwo }),
            };
        });
}
