/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07,
    FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07$,
} from "./fortytwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07";
import { PayrollReportInvoice, PayrollReportInvoice$ } from "./payrollreportinvoice";
import { z } from "zod";

export type PayrollReportResponse = {
    invoices: Array<PayrollReportInvoice>;
    parentInvoice: FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07;
};

/** @internal */
export namespace PayrollReportResponse$ {
    export type Inbound = {
        invoices: Array<PayrollReportInvoice$.Inbound>;
        parentInvoice: FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07$.Inbound;
    };

    export const inboundSchema: z.ZodType<PayrollReportResponse, z.ZodTypeDef, Inbound> = z
        .object({
            invoices: z.array(PayrollReportInvoice$.inboundSchema),
            parentInvoice:
                FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07$.inboundSchema,
        })
        .transform((v) => {
            return {
                invoices: v.invoices,
                parentInvoice: v.parentInvoice,
            };
        });

    export type Outbound = {
        invoices: Array<PayrollReportInvoice$.Outbound>;
        parentInvoice: FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PayrollReportResponse> = z
        .object({
            invoices: z.array(PayrollReportInvoice$.outboundSchema),
            parentInvoice:
                FortyTwof004011439ceedfeb392c84d36ad40443a5a0446d1efa02369c56e930a1c07$.outboundSchema,
        })
        .transform((v) => {
            return {
                invoices: v.invoices,
                parentInvoice: v.parentInvoice,
            };
        });
}
