/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Sixad3f4f624fb518510130e879729b00ed8c237d1cebc5477abf34ac340a6424d = {
    expenseAccountId?: string | null | undefined;
    itemId?: string | null | undefined;
};

/** @internal */
export namespace Sixad3f4f624fb518510130e879729b00ed8c237d1cebc5477abf34ac340a6424d$ {
    export type Inbound = {
        expenseAccountId?: string | null | undefined;
        itemId?: string | null | undefined;
    };

    export const inboundSchema: z.ZodType<
        Sixad3f4f624fb518510130e879729b00ed8c237d1cebc5477abf34ac340a6424d,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            expenseAccountId: z.nullable(z.string()).optional(),
            itemId: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.expenseAccountId === undefined
                    ? null
                    : { expenseAccountId: v.expenseAccountId }),
                ...(v.itemId === undefined ? null : { itemId: v.itemId }),
            };
        });

    export type Outbound = {
        expenseAccountId?: string | null | undefined;
        itemId?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        Sixad3f4f624fb518510130e879729b00ed8c237d1cebc5477abf34ac340a6424d
    > = z
        .object({
            expenseAccountId: z.nullable(z.string()).optional(),
            itemId: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.expenseAccountId === undefined
                    ? null
                    : { expenseAccountId: v.expenseAccountId }),
                ...(v.itemId === undefined ? null : { itemId: v.itemId }),
            };
        });
}
