/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum Health {
    Healthy = "Healthy",
    Unhealthy = "Unhealthy",
    Unknown = "Unknown",
}

export class SixtyThreeb104af49f941a112cbf8987ad15398351abae11639690db561784bb86bb07e extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "details" })
    details?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "health" })
    health: Health;
}
