/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Fourc638629a9ab57d496147964335fd74ca94b1bb4ca82380d39ab39d0d4b3c1c6 extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "expiresAt" })
    expiresAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;
}
