/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CompanyLinks extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "instagramUrl" })
    instagramUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "linkedInUrl" })
    linkedInUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "otherUrl" })
    otherUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "twitterUrl" })
    twitterUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "websiteUrl" })
    websiteUrl?: string;
}
