/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type DefaultPaymentMethod = {
    accountId?: string | null | undefined;
    defaultPaymentWeekday?: number | null | undefined;
    paymentMethodId?: string | null | undefined;
};

/** @internal */
export namespace DefaultPaymentMethod$ {
    export type Inbound = {
        accountId?: string | null | undefined;
        defaultPaymentWeekday?: number | null | undefined;
        paymentMethodId?: string | null | undefined;
    };

    export const inboundSchema: z.ZodType<DefaultPaymentMethod, z.ZodTypeDef, Inbound> = z
        .object({
            accountId: z.nullable(z.string()).optional(),
            defaultPaymentWeekday: z.nullable(z.number()).optional(),
            paymentMethodId: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.accountId === undefined ? null : { accountId: v.accountId }),
                ...(v.defaultPaymentWeekday === undefined
                    ? null
                    : { defaultPaymentWeekday: v.defaultPaymentWeekday }),
                ...(v.paymentMethodId === undefined
                    ? null
                    : { paymentMethodId: v.paymentMethodId }),
            };
        });

    export type Outbound = {
        accountId?: string | null | undefined;
        defaultPaymentWeekday?: number | null | undefined;
        paymentMethodId?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DefaultPaymentMethod> = z
        .object({
            accountId: z.nullable(z.string()).optional(),
            defaultPaymentWeekday: z.nullable(z.number()).optional(),
            paymentMethodId: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return {
                ...(v.accountId === undefined ? null : { accountId: v.accountId }),
                ...(v.defaultPaymentWeekday === undefined
                    ? null
                    : { defaultPaymentWeekday: v.defaultPaymentWeekday }),
                ...(v.paymentMethodId === undefined
                    ? null
                    : { paymentMethodId: v.paymentMethodId }),
            };
        });
}
