/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NextgenSubscriptionDiscount } from "./nextgensubscriptiondiscount";
import { NextgenSubscriptionPlan } from "./nextgensubscriptionplan";
import { NextgenSubscriptionPrice } from "./nextgensubscriptionprice";
import { UserRoles } from "./userroles";
import { Expose, Type } from "class-transformer";

export enum NextgenSubscriptionResponseStatus {
    Active = "Active",
    Canceled = "Canceled",
}

export enum NextgenSubscriptionResponseTerm {
    Yearly = "Yearly",
    Monthly = "Monthly",
}

export enum NextgenSubscriptionResponseUnits {
    Month = "Month",
}

export class NextgenSubscriptionResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cancelAtPeriodEnd" })
    cancelAtPeriodEnd?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "createdAt" })
    createdAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "currentPeriodEnd" })
    currentPeriodEnd: string;

    @SpeakeasyMetadata()
    @Expose({ name: "currentPeriodStart" })
    currentPeriodStart: string;

    @SpeakeasyMetadata({ elemType: NextgenSubscriptionDiscount })
    @Expose({ name: "discounts" })
    @Type(() => NextgenSubscriptionDiscount)
    discounts: NextgenSubscriptionDiscount[];

    @SpeakeasyMetadata()
    @Expose({ name: "eventActors" })
    eventActors: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "gracePeriodEnd" })
    gracePeriodEnd: string;

    @SpeakeasyMetadata()
    @Expose({ name: "labels" })
    labels: Record<string, string>;

    @SpeakeasyMetadata()
    @Expose({ name: "memberId" })
    memberId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "plan" })
    @Type(() => NextgenSubscriptionPlan)
    plan: NextgenSubscriptionPlan;

    @SpeakeasyMetadata()
    @Expose({ name: "planId" })
    planId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    @Type(() => NextgenSubscriptionPrice)
    price: NextgenSubscriptionPrice;

    @SpeakeasyMetadata()
    @Expose({ name: "quantity" })
    quantity: number;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: NextgenSubscriptionResponseStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "subscriptionEndDate" })
    subscriptionEndDate: string;

    @SpeakeasyMetadata()
    @Expose({ name: "subscriptionId" })
    subscriptionId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "subscriptionStart" })
    subscriptionStart: string;

    @SpeakeasyMetadata()
    @Expose({ name: "term" })
    term: NextgenSubscriptionResponseTerm;

    @SpeakeasyMetadata()
    @Expose({ name: "units" })
    units: NextgenSubscriptionResponseUnits;

    @SpeakeasyMetadata()
    @Expose({ name: "updatedAt" })
    updatedAt: string;

    @SpeakeasyMetadata()
    @Expose({ name: "userRoles" })
    @Type(() => UserRoles)
    userRoles: UserRoles;
}
