/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum UserAccountType {
    Member = "member",
    Enterprise = "enterprise",
    LessThanNilGreaterThan = "<nil>",
}

export class Ninee97e63e736df301658ebeeab7f4fe84f3aeaa73800d3e4863801a3eb026df4b extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "userAccountType" })
    userAccountType?: UserAccountType;
}
