/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum SubscriptionGrantUpdateRequestPackage {
    None = "None",
    Benefits = "Benefits",
    Essentials = "Essentials",
    Professional = "Professional",
    Corporate = "Corporate",
}

export enum SubscriptionGrantUpdateRequestPackageTier {
    Basic = "Basic",
    Premium = "Premium",
}

export type SubscriptionGrantUpdateRequest = {
    package?: SubscriptionGrantUpdateRequestPackage | null | undefined;
    packageTier?: SubscriptionGrantUpdateRequestPackageTier | null | undefined;
};

/** @internal */
export const SubscriptionGrantUpdateRequestPackage$ = z.nativeEnum(
    SubscriptionGrantUpdateRequestPackage
);

/** @internal */
export const SubscriptionGrantUpdateRequestPackageTier$ = z.nativeEnum(
    SubscriptionGrantUpdateRequestPackageTier
);

/** @internal */
export namespace SubscriptionGrantUpdateRequest$ {
    export type Inbound = {
        package?: SubscriptionGrantUpdateRequestPackage | null | undefined;
        packageTier?: SubscriptionGrantUpdateRequestPackageTier | null | undefined;
    };

    export const inboundSchema: z.ZodType<SubscriptionGrantUpdateRequest, z.ZodTypeDef, Inbound> = z
        .object({
            package: z.nullable(SubscriptionGrantUpdateRequestPackage$).optional(),
            packageTier: z.nullable(SubscriptionGrantUpdateRequestPackageTier$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.package === undefined ? null : { package: v.package }),
                ...(v.packageTier === undefined ? null : { packageTier: v.packageTier }),
            };
        });

    export type Outbound = {
        package?: SubscriptionGrantUpdateRequestPackage | null | undefined;
        packageTier?: SubscriptionGrantUpdateRequestPackageTier | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SubscriptionGrantUpdateRequest> =
        z
            .object({
                package: z.nullable(SubscriptionGrantUpdateRequestPackage$).optional(),
                packageTier: z.nullable(SubscriptionGrantUpdateRequestPackageTier$).optional(),
            })
            .transform((v) => {
                return {
                    ...(v.package === undefined ? null : { package: v.package }),
                    ...(v.packageTier === undefined ? null : { packageTier: v.packageTier }),
                };
            });
}
