/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Address } from "./address";
import { Company } from "./company";
import { Expose, Type } from "class-transformer";

export class TwentyThreed776fc12e56286a20f36065e4f942c43a28218a62eb2f211116c130deb74eb extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    @Type(() => Address)
    address?: Address;

    @SpeakeasyMetadata()
    @Expose({ name: "company" })
    @Type(() => Company)
    company?: Company;

    @SpeakeasyMetadata()
    @Expose({ name: "logoUrl" })
    logoUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ssnLastFour" })
    ssnLastFour?: string;
}
