/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UserNotificationSettings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "newsletters" })
    newsletters?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "reviewNotifications" })
    reviewNotifications?: boolean;
}
