/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class A71f30be878693b235f8c5f1650be03c9920ca9821526545760476436104c9dc extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deductionIds" })
    deductionIds: any;
}
