name: Release Wingspan integrations library
'on':
  push:
    paths:
    - "integrations/RELEASES.md"
    branches:
    - staging
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      create_release: true
      publish_typescript: true
    secrets:
      github_access_token: ${{ secrets.ADMIN_PERSONAL_ACCESS_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      npm_token: ${{ secrets.NPM_REGISTRY_TOKEN }}
